export GIT_BYPASS = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000003

# Define target output
target: dcp

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

export PROJECT = UdpDebugBridgeStub

# Override the defaults
export TOP_DIR = $(abspath $(PROJ_DIR)/../../../../../)

# Use top level makefile
include ../../../../ruckus/system_vivado.mk
