## please copy over all contents of the XDC when it is merged with othe XDC files ##

## Clock constraint for input system clock which drives MMCM for the design

## The frequency of the input clock is as per GUI selected input clock period

## Below pin LOC constraints are for system clock and system reset and

## memory related pins

set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[39]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[38]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ck_p[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[36]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[34]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ck_n[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[33]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[32]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[37]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[35]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ck_p[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ba[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[31]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[30]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[27]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[26]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[28]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ck_n[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[13]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[24]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[29]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ba[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ba[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[44]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[45]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[60]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[61]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[62]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[25]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[20]" ]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [ get_ports "c0_ddr3_reset_n" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_cs_n[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_addr[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[46]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[58]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[59]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[63]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[18]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[23]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[22]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[21]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_ras_n" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_cs_n[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_cke[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_cke[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[42]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[43]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[47]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[56]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[57]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[19]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[16]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_odt[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_cas_n" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_we_n" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[52]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[54]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[13]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[17]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_odt[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[40]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[41]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[53]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[55]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dm[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[50]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[51]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_p[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[48]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dq[49]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr3_dqs_n[6]" ]




set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[39]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[38]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[4]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[0]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_ck_p[0]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[4]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[4]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[36]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[34]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[1]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_ck_n[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[4]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[5]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[8]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[9]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[33]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[32]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[37]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[35]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_ck_p[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[6]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[10]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[11]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_ba[2]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[31]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[30]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[27]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[26]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[28]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_ck_n[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[2]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[7]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[12]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[13]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[24]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[3]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[29]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[3]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_ba[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_ba[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[14]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[5]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[44]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[45]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[60]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[61]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[7]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[62]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[3]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[3]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[25]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[20]" ]
set_property IOSTANDARD SSTL15 [ get_ports "c0_ddr3_reset_n" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_cs_n[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_addr[15]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[46]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[7]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[58]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[59]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[7]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[63]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[18]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[23]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[22]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[21]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_ras_n" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_cs_n[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_cke[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_cke[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[42]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[43]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[47]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[56]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[57]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[2]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[19]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[2]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[2]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[16]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_odt[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_cas_n" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_we_n" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[5]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[5]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[52]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[54]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[13]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[12]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[10]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[17]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_odt[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[2]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[40]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[41]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[53]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[55]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[11]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[1]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[8]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[1]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[6]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[3]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dm[6]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[50]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[51]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[6]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[15]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[14]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[9]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_p[0]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[0]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[7]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[4]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[5]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[48]" ]
set_property IOSTANDARD SSTL15_DCI [ get_ports "c0_ddr3_dq[49]" ]
set_property IOSTANDARD DIFF_SSTL15_DCI [ get_ports "c0_ddr3_dqs_n[6]" ]


## This signal is static signals. Once asserted it will stay HIGH.

## The multi cycle path constraint is added to improve the timing.

set_multicycle_path -setup 8 -from [get_pins */u_ddr_cal_top/calDone*/C]
set_multicycle_path -end -hold 7 -from [get_pins */u_ddr_cal_top/calDone*/C]


## These signals once asserted, stays asserted for multiple clock cycles.

## False path constraint is added to improve the HOLD timing.

set_false_path -hold -to [get_pins */*/*/*/*/*.u_xiphy_control/xiphy_control/RIU_ADDR*]
set_false_path -hold -to [get_pins */*/*/*/*/*.u_xiphy_control/xiphy_control/RIU_WR_DATA*]


set_property SLEW FAST  [get_ports {c0_ddr3_addr[*] c0_ddr3_ba[*] c0_ddr3_cke[*] c0_ddr3_ck_p[*] c0_ddr3_ck_n[*] c0_ddr3_cas_n c0_ddr3_odt[*] c0_ddr3_ras_n c0_ddr3_we_n c0_ddr3_dq[*] c0_ddr3_dqs_p[*] c0_ddr3_dqs_n[*]}]
set_property SLEW SLOW  [get_ports {c0_ddr3_reset_n}]
set_property IBUF_LOW_PWR FALSE  [get_ports {c0_ddr3_dq[*] c0_ddr3_dqs_p[*] c0_ddr3_dqs_n[*]}]
set_property ODT RTT_40  [get_ports {c0_ddr3_dq[*] c0_ddr3_dqs_p[*] c0_ddr3_dqs_n[*]}]
set_property SLEW FAST  [get_ports {c0_ddr3_cs_n[*]}]
set_property DATA_RATE SDR  [get_ports {c0_ddr3_cs_n[*]}]
set_property SLEW FAST  [get_ports {c0_ddr3_dm[*]}]
set_property DATA_RATE DDR  [get_ports {c0_ddr3_dm[*]}]
set_property DATA_RATE SDR  [get_ports {c0_ddr3_addr[*] c0_ddr3_ba[*] c0_ddr3_cke[*] c0_ddr3_cas_n c0_ddr3_odt[*] c0_ddr3_ras_n c0_ddr3_we_n }]
set_property DATA_RATE DDR  [get_ports {c0_ddr3_dq[*] c0_ddr3_dqs_p[*] c0_ddr3_dqs_n[*] c0_ddr3_ck_p[*] c0_ddr3_ck_n[*]}]
set_property DATA_RATE SDR  [get_ports {c0_ddr3_reset_n}]
## Multi-cycle path constraints for Fabric - RIU clock domain crossing signals
set_max_delay 5.0 -datapath_only -from [get_pins */*/*/u_ddr_cal_addr_decode/io_ready_lvl_reg/C] -to [get_pins */u_io_ready_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 5.0 -datapath_only -from [get_pins */*/*/u_ddr_cal_addr_decode/io_read_data_reg[*]/C] -to [get_pins */u_io_read_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/*/phy_ready_riuclk_reg/C] -to [get_pins */u_phy2clb_phy_ready_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/*/bisc_complete_riuclk_reg/C] -to [get_pins */u_phy2clb_bisc_complete_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_addr_strobe_lvl_riuclk_reg/C] -to [get_pins */u_io_addr_strobe_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_write_strobe_riuclk_reg/C] -to [get_pins */u_io_write_strobe_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_address_riuclk_reg[*]/C] -to [get_pins */u_io_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_write_data_riuclk_reg[*]/C] -to [get_pins */u_io_write_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */en_vtc_in_reg/C] -to [get_pins */u_en_vtc_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */*/riu2clb_valid_r1_riuclk_reg[*]/C] -to [get_pins */u_riu2clb_valid_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_fixdly_rdy_low_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_fixdly_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_fixdly_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_fixdly_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_phy_rdy_low_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_phy_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_phy_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_phy_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins */rst_r1_reg/C] -to [get_pins */u_fab_rst_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/clb2phy_t_b_addr_riuclk_reg/C] -to [get_pins  */*/*/clb2phy_t_b_addr_i_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_en_lvl_reg/C] -to [get_pins  */*/*/*/u_slave_en_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_we_r_reg/C] -to [get_pins  */*/*/*/u_slave_we_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_addr_r_reg[*]/C] -to [get_pins  */*/*/*/u_slave_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_di_r_reg[*]/C] -to [get_pins  */*/*/*/u_slave_di_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_rdy_cptd_sclk_reg/C] -to [get_pins  */*/*/*/u_slave_rdy_cptd_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 12.0 -datapath_only -from [get_pins */*/*/*/slave_rdy_lvl_fclk_reg/C] -to [get_pins  */*/*/*/u_slave_rdy_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 12.0 -datapath_only -from [get_pins */*/*/*/slave_do_fclk_reg[*]/C] -to [get_pins  */*/*/*/u_slave_do_sync/SYNC[*].sync_reg_reg[0]/D]
set_false_path -through [get_pins u_ddr3_infrastructure/sys_rst]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_riu_sync_r_reg[0]/D]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_riu_div_reg/C] -to [get_pins */rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_mb_reg/C]      -to [get_pins */rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_riu_div_reg/C] -to [get_pins */rst_riu_sync_r_reg[0]/D]
## These below commands are used to create Interface ports for controller.

create_interface -quiet interface_MigCore
set_property interface interface_MigCore [get_ports [list {c0_ddr3_dq[39]} {c0_ddr3_dq[38]} {c0_ddr3_dm[4]} {c0_ddr3_addr[0]} {c0_ddr3_ck_p[0]} {c0_ddr3_dqs_n[4]} {c0_ddr3_dqs_p[4]} {c0_ddr3_dq[36]} {c0_ddr3_dq[34]} {c0_ddr3_addr[1]} {c0_ddr3_ck_n[0]} {c0_ddr3_addr[4]} {c0_ddr3_addr[5]} {c0_ddr3_addr[8]} {c0_ddr3_addr[9]} {c0_ddr3_dq[33]} {c0_ddr3_dq[32]} {c0_ddr3_dq[37]} {c0_ddr3_dq[35]} {c0_ddr3_ck_p[1]} {c0_ddr3_addr[6]} {c0_ddr3_addr[10]} {c0_ddr3_addr[11]} {c0_ddr3_ba[2]} {c0_ddr3_dq[31]} {c0_ddr3_dq[30]} {c0_ddr3_dq[27]} {c0_ddr3_dq[26]} {c0_ddr3_dq[28]} {c0_ddr3_ck_n[1]} {c0_ddr3_addr[2]} {c0_ddr3_addr[7]} {c0_ddr3_addr[12]} {c0_ddr3_addr[13]} {c0_ddr3_dq[24]} {c0_ddr3_dm[3]} {c0_ddr3_dq[29]} {c0_ddr3_addr[3]} {c0_ddr3_ba[0]} {c0_ddr3_ba[1]} {c0_ddr3_addr[14]} {c0_ddr3_dm[5]} {c0_ddr3_dq[44]} {c0_ddr3_dq[45]} {c0_ddr3_dq[60]} {c0_ddr3_dq[61]} {c0_ddr3_dqs_p[7]} {c0_ddr3_dq[62]} {c0_ddr3_dqs_n[3]} {c0_ddr3_dqs_p[3]} {c0_ddr3_dq[25]} {c0_ddr3_dq[20]} c0_ddr3_reset_n {c0_ddr3_cs_n[0]} {c0_ddr3_addr[15]} {c0_ddr3_dq[46]} {c0_ddr3_dm[7]} {c0_ddr3_dq[58]} {c0_ddr3_dq[59]} {c0_ddr3_dqs_n[7]} {c0_ddr3_dq[63]} {c0_ddr3_dq[18]} {c0_ddr3_dq[23]} {c0_ddr3_dq[22]} {c0_ddr3_dq[21]} c0_ddr3_ras_n {c0_ddr3_cs_n[1]} {c0_ddr3_cke[0]} {c0_ddr3_cke[1]} {c0_ddr3_dq[42]} {c0_ddr3_dq[43]} {c0_ddr3_dq[47]} {c0_ddr3_dq[56]} {c0_ddr3_dq[57]} {c0_ddr3_dm[2]} {c0_ddr3_dq[19]} {c0_ddr3_dqs_n[2]} {c0_ddr3_dqs_p[2]} {c0_ddr3_dq[16]} {c0_ddr3_odt[0]} c0_ddr3_cas_n c0_ddr3_we_n {c0_ddr3_dqs_p[5]} {c0_ddr3_dqs_n[5]} {c0_ddr3_dq[52]} {c0_ddr3_dq[54]} {c0_ddr3_dq[13]} {c0_ddr3_dq[12]} {c0_ddr3_dq[10]} {c0_ddr3_dq[17]} {c0_ddr3_odt[1]} {c0_ddr3_dm[0]} {c0_ddr3_dq[0]} {c0_ddr3_dq[2]} {c0_ddr3_dq[40]} {c0_ddr3_dq[41]} {c0_ddr3_dq[53]} {c0_ddr3_dq[55]} {c0_ddr3_dm[1]} {c0_ddr3_dq[11]} {c0_ddr3_dqs_n[1]} {c0_ddr3_dqs_p[1]} {c0_ddr3_dq[8]} {c0_ddr3_dq[1]} {c0_ddr3_dq[6]} {c0_ddr3_dq[3]} {c0_ddr3_dm[6]} {c0_ddr3_dq[50]} {c0_ddr3_dq[51]} {c0_ddr3_dqs_p[6]} {c0_ddr3_dq[15]} {c0_ddr3_dq[14]} {c0_ddr3_dq[9]} {c0_ddr3_dqs_p[0]} {c0_ddr3_dqs_n[0]} {c0_ddr3_dq[7]} {c0_ddr3_dq[4]} {c0_ddr3_dq[5]} {c0_ddr3_dq[48]} {c0_ddr3_dq[49]} {c0_ddr3_dqs_n[6]}]]
