-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.3 (lin64) Build 2018833 Wed Oct  4 19:58:07 MDT 2017
-- Date        : Sun Dec 31 14:00:57 2017
-- Host        : rdsrv221 running 64-bit Red Hat Enterprise Linux Server release 6.9 (Santiago)
-- Command     : write_vhdl -force -mode synth_stub
--               /u1/strauman/amc-carrier-project-template/firmware/submodules/amc-carrier-core/AmcCarrierCore/dcp/images/AmcCarrierCore_stub.vhd
-- Design      : AmcCarrierCore
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcku040-ffva1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AmcCarrierCore is
  Port ( 
    timingClk : in STD_LOGIC;
    timingRst : in STD_LOGIC;
    \timingBusIntf[strobe]\ : out STD_LOGIC;
    \timingBusIntf[valid]\ : out STD_LOGIC;
    \timingBusIntf[message][version]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][pulseId]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][timeStamp]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][fixedRates]\ : out STD_LOGIC_VECTOR ( 9 downto 0 );
    \timingBusIntf[message][acRates]\ : out STD_LOGIC_VECTOR ( 5 downto 0 );
    \timingBusIntf[message][acTimeSlot]\ : out STD_LOGIC_VECTOR ( 2 downto 0 );
    \timingBusIntf[message][acTimeSlotPhase]\ : out STD_LOGIC_VECTOR ( 11 downto 0 );
    \timingBusIntf[message][resync]\ : out STD_LOGIC;
    \timingBusIntf[message][beamRequest]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[message][beamEnergy][0]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][beamEnergy][1]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][beamEnergy][2]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][beamEnergy][3]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][photonWavelen][0]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][photonWavelen][1]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][syncStatus]\ : out STD_LOGIC;
    \timingBusIntf[message][mpsValid]\ : out STD_LOGIC;
    \timingBusIntf[message][bcsFault]\ : out STD_LOGIC_VECTOR ( 0 to 0 );
    \timingBusIntf[message][mpsLimit]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][mpsClass][0]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][1]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][2]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][3]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][4]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][5]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][6]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][7]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][8]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][9]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][10]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][11]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][12]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][13]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][14]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][mpsClass][15]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingBusIntf[message][bsaInit]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][bsaActive]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][bsaAvgDone]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][bsaDone]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[message][control][0]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][1]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][2]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][3]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][4]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][5]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][6]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][7]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][8]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][9]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][10]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][11]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][12]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][13]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][14]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][15]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][16]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[message][control][17]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[stream][pulseId]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[stream][eventCodes]\ : out STD_LOGIC_VECTOR ( 255 downto 0 );
    \timingBusIntf[stream][dbuff][dtype]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[stream][dbuff][version]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[stream][dbuff][dmod]\ : out STD_LOGIC_VECTOR ( 191 downto 0 );
    \timingBusIntf[stream][dbuff][epicsTime]\ : out STD_LOGIC_VECTOR ( 63 downto 0 );
    \timingBusIntf[stream][dbuff][edefAvgDn]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[stream][dbuff][edefMinor]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[stream][dbuff][edefMajor]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[stream][dbuff][edefInit]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingBusIntf[v1][linkUp]\ : out STD_LOGIC;
    \timingBusIntf[v1][gtRxData]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingBusIntf[v1][gtRxDataK]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingBusIntf[v1][gtRxDispErr]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingBusIntf[v1][gtRxDecErr]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingBusIntf[v2][linkUp]\ : out STD_LOGIC;
    \timingPhy[dataK]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingPhy[data]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \timingPhy[control][reset]\ : in STD_LOGIC;
    \timingPhy[control][inhibit]\ : in STD_LOGIC;
    \timingPhy[control][polarity]\ : in STD_LOGIC;
    \timingPhy[control][bufferByRst]\ : in STD_LOGIC;
    \timingPhy[control][pllReset]\ : in STD_LOGIC;
    timingPhyClk : out STD_LOGIC;
    timingPhyRst : out STD_LOGIC;
    timingRefClk : out STD_LOGIC;
    timingRefClkDiv2 : out STD_LOGIC;
    diagnosticClk : in STD_LOGIC;
    diagnosticRst : in STD_LOGIC;
    \diagnosticBus[strobe]\ : in STD_LOGIC;
    \diagnosticBus[data][31]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][30]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][29]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][28]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][27]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][26]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][25]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][24]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][23]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][22]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][21]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][20]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][19]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][18]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][17]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][16]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][15]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][14]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][13]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][12]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][11]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][10]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][9]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][8]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][7]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][6]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][5]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][4]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][3]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][2]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][1]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[data][0]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[sevr][31]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][30]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][29]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][28]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][27]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][26]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][25]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][24]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][23]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][22]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][21]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][20]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][19]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][18]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][17]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][16]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][15]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][14]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][13]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][12]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][11]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][10]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][9]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][8]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][7]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][6]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][5]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][4]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][3]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][2]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][1]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[sevr][0]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \diagnosticBus[fixed]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[mpsIgnore]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[timingMessage][version]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][pulseId]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][timeStamp]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][fixedRates]\ : in STD_LOGIC_VECTOR ( 9 downto 0 );
    \diagnosticBus[timingMessage][acRates]\ : in STD_LOGIC_VECTOR ( 5 downto 0 );
    \diagnosticBus[timingMessage][acTimeSlot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \diagnosticBus[timingMessage][acTimeSlotPhase]\ : in STD_LOGIC_VECTOR ( 11 downto 0 );
    \diagnosticBus[timingMessage][resync]\ : in STD_LOGIC;
    \diagnosticBus[timingMessage][beamRequest]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \diagnosticBus[timingMessage][beamEnergy][0]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][beamEnergy][1]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][beamEnergy][2]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][beamEnergy][3]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][photonWavelen][0]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][photonWavelen][1]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][syncStatus]\ : in STD_LOGIC;
    \diagnosticBus[timingMessage][mpsValid]\ : in STD_LOGIC;
    \diagnosticBus[timingMessage][bcsFault]\ : in STD_LOGIC_VECTOR ( 0 to 0 );
    \diagnosticBus[timingMessage][mpsLimit]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][0]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][1]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][2]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][3]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][4]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][5]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][6]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][7]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][8]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][9]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][10]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][11]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][12]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][13]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][14]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][mpsClass][15]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \diagnosticBus[timingMessage][bsaInit]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][bsaActive]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][bsaAvgDone]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][bsaDone]\ : in STD_LOGIC_VECTOR ( 63 downto 0 );
    \diagnosticBus[timingMessage][control][0]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][1]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][2]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][3]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][4]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][5]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][6]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][7]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][8]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][9]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][10]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][11]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][12]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][13]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][14]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][15]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][16]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \diagnosticBus[timingMessage][control][17]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    waveformClk : out STD_LOGIC;
    waveformRst : out STD_LOGIC;
    \obAppWaveformMasters[1][3][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][3][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][3][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][3][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][3][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][3][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][3][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][3][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][2][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][2][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][2][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][2][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][2][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][2][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][2][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][2][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][1][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][1][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][1][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][1][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][1][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][1][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][1][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][1][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][0][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][0][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[1][0][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][0][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[1][0][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[1][0][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][0][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[1][0][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][3][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][3][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][3][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][3][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][3][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][3][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][3][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][3][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][2][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][2][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][2][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][2][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][2][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][2][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][2][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][2][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][1][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][1][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][1][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][1][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][1][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][1][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][1][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][1][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][0][tValid]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][0][tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformMasters[0][0][tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][0][tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppWaveformMasters[0][0][tLast]\ : in STD_LOGIC;
    \obAppWaveformMasters[0][0][tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][0][tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppWaveformMasters[0][0][tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppWaveformSlaves[1][3][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][3][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][3][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][3][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][2][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][2][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][2][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][2][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][1][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][1][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][1][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][1][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][0][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][0][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][0][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[1][0][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][3][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][3][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][3][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][3][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][2][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][2][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][2][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][2][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][1][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][1][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][1][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][1][ctrl][idle]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][0][slave][tReady]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][0][ctrl][pause]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][0][ctrl][overflow]\ : out STD_LOGIC;
    \obAppWaveformSlaves[0][0][ctrl][idle]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][3][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][3][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][3][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][3][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][3][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][3][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][3][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][3][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][2][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][2][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][2][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][2][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][2][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][2][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][2][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][2][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][1][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][1][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][1][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][1][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][1][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][1][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][1][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][1][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][0][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][0][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[1][0][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][0][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[1][0][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[1][0][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][0][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[1][0][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][3][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][3][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][3][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][3][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][3][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][3][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][3][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][3][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][2][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][2][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][2][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][2][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][2][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][2][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][2][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][2][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][1][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][1][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][1][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][1][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][1][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][1][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][1][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][1][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][0][tValid]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][0][tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformMasters[0][0][tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][0][tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppWaveformMasters[0][0][tLast]\ : out STD_LOGIC;
    \ibAppWaveformMasters[0][0][tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][0][tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppWaveformMasters[0][0][tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppWaveformSlaves[1][3][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][3][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][3][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][3][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][2][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][2][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][2][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][2][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][1][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][1][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][1][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][1][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][0][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][0][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][0][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[1][0][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][3][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][3][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][3][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][3][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][2][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][2][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][2][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][2][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][1][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][1][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][1][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][1][ctrl][idle]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][0][slave][tReady]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][0][ctrl][pause]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][0][ctrl][overflow]\ : in STD_LOGIC;
    \ibAppWaveformSlaves[0][0][ctrl][idle]\ : in STD_LOGIC;
    \obBpMsgClientMaster[tValid]\ : in STD_LOGIC;
    \obBpMsgClientMaster[tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obBpMsgClientMaster[tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obBpMsgClientMaster[tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obBpMsgClientMaster[tLast]\ : in STD_LOGIC;
    \obBpMsgClientMaster[tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obBpMsgClientMaster[tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obBpMsgClientMaster[tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obBpMsgClientSlave[tReady]\ : out STD_LOGIC;
    \ibBpMsgClientMaster[tValid]\ : out STD_LOGIC;
    \ibBpMsgClientMaster[tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibBpMsgClientMaster[tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibBpMsgClientMaster[tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibBpMsgClientMaster[tLast]\ : out STD_LOGIC;
    \ibBpMsgClientMaster[tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibBpMsgClientMaster[tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibBpMsgClientMaster[tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibBpMsgClientSlave[tReady]\ : in STD_LOGIC;
    \obBpMsgServerMaster[tValid]\ : in STD_LOGIC;
    \obBpMsgServerMaster[tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obBpMsgServerMaster[tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obBpMsgServerMaster[tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obBpMsgServerMaster[tLast]\ : in STD_LOGIC;
    \obBpMsgServerMaster[tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obBpMsgServerMaster[tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obBpMsgServerMaster[tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obBpMsgServerSlave[tReady]\ : out STD_LOGIC;
    \ibBpMsgServerMaster[tValid]\ : out STD_LOGIC;
    \ibBpMsgServerMaster[tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibBpMsgServerMaster[tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibBpMsgServerMaster[tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibBpMsgServerMaster[tLast]\ : out STD_LOGIC;
    \ibBpMsgServerMaster[tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibBpMsgServerMaster[tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibBpMsgServerMaster[tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibBpMsgServerSlave[tReady]\ : in STD_LOGIC;
    \obAppDebugMaster[tValid]\ : in STD_LOGIC;
    \obAppDebugMaster[tData]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppDebugMaster[tStrb]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppDebugMaster[tKeep]\ : in STD_LOGIC_VECTOR ( 15 downto 0 );
    \obAppDebugMaster[tLast]\ : in STD_LOGIC;
    \obAppDebugMaster[tDest]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppDebugMaster[tId]\ : in STD_LOGIC_VECTOR ( 7 downto 0 );
    \obAppDebugMaster[tUser]\ : in STD_LOGIC_VECTOR ( 127 downto 0 );
    \obAppDebugSlave[tReady]\ : out STD_LOGIC;
    \ibAppDebugMaster[tValid]\ : out STD_LOGIC;
    \ibAppDebugMaster[tData]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppDebugMaster[tStrb]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppDebugMaster[tKeep]\ : out STD_LOGIC_VECTOR ( 15 downto 0 );
    \ibAppDebugMaster[tLast]\ : out STD_LOGIC;
    \ibAppDebugMaster[tDest]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppDebugMaster[tId]\ : out STD_LOGIC_VECTOR ( 7 downto 0 );
    \ibAppDebugMaster[tUser]\ : out STD_LOGIC_VECTOR ( 127 downto 0 );
    \ibAppDebugSlave[tReady]\ : in STD_LOGIC;
    recTimingClk : out STD_LOGIC;
    recTimingRst : out STD_LOGIC;
    ref156MHzClk : out STD_LOGIC;
    ref156MHzRst : out STD_LOGIC;
    gthFabClk : out STD_LOGIC;
    \axilReadMasters[1][araddr]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilReadMasters[1][arprot]\ : out STD_LOGIC_VECTOR ( 2 downto 0 );
    \axilReadMasters[1][arvalid]\ : out STD_LOGIC;
    \axilReadMasters[1][rready]\ : out STD_LOGIC;
    \axilReadMasters[0][araddr]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilReadMasters[0][arprot]\ : out STD_LOGIC_VECTOR ( 2 downto 0 );
    \axilReadMasters[0][arvalid]\ : out STD_LOGIC;
    \axilReadMasters[0][rready]\ : out STD_LOGIC;
    \axilReadSlaves[1][arready]\ : in STD_LOGIC;
    \axilReadSlaves[1][rdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilReadSlaves[1][rresp]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \axilReadSlaves[1][rvalid]\ : in STD_LOGIC;
    \axilReadSlaves[0][arready]\ : in STD_LOGIC;
    \axilReadSlaves[0][rdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilReadSlaves[0][rresp]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \axilReadSlaves[0][rvalid]\ : in STD_LOGIC;
    \axilWriteMasters[1][awaddr]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilWriteMasters[1][awprot]\ : out STD_LOGIC_VECTOR ( 2 downto 0 );
    \axilWriteMasters[1][awvalid]\ : out STD_LOGIC;
    \axilWriteMasters[1][wdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilWriteMasters[1][wstrb]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \axilWriteMasters[1][wvalid]\ : out STD_LOGIC;
    \axilWriteMasters[1][bready]\ : out STD_LOGIC;
    \axilWriteMasters[0][awaddr]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilWriteMasters[0][awprot]\ : out STD_LOGIC_VECTOR ( 2 downto 0 );
    \axilWriteMasters[0][awvalid]\ : out STD_LOGIC;
    \axilWriteMasters[0][wdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \axilWriteMasters[0][wstrb]\ : out STD_LOGIC_VECTOR ( 3 downto 0 );
    \axilWriteMasters[0][wvalid]\ : out STD_LOGIC;
    \axilWriteMasters[0][bready]\ : out STD_LOGIC;
    \axilWriteSlaves[1][awready]\ : in STD_LOGIC;
    \axilWriteSlaves[1][wready]\ : in STD_LOGIC;
    \axilWriteSlaves[1][bresp]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \axilWriteSlaves[1][bvalid]\ : in STD_LOGIC;
    \axilWriteSlaves[0][awready]\ : in STD_LOGIC;
    \axilWriteSlaves[0][wready]\ : in STD_LOGIC;
    \axilWriteSlaves[0][bresp]\ : in STD_LOGIC_VECTOR ( 1 downto 0 );
    \axilWriteSlaves[0][bvalid]\ : in STD_LOGIC;
    \ethReadMaster[araddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ethReadMaster[arprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \ethReadMaster[arvalid]\ : in STD_LOGIC;
    \ethReadMaster[rready]\ : in STD_LOGIC;
    \ethReadSlave[arready]\ : out STD_LOGIC;
    \ethReadSlave[rdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \ethReadSlave[rresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \ethReadSlave[rvalid]\ : out STD_LOGIC;
    \ethWriteMaster[awaddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ethWriteMaster[awprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \ethWriteMaster[awvalid]\ : in STD_LOGIC;
    \ethWriteMaster[wdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ethWriteMaster[wstrb]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \ethWriteMaster[wvalid]\ : in STD_LOGIC;
    \ethWriteMaster[bready]\ : in STD_LOGIC;
    \ethWriteSlave[awready]\ : out STD_LOGIC;
    \ethWriteSlave[wready]\ : out STD_LOGIC;
    \ethWriteSlave[bresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \ethWriteSlave[bvalid]\ : out STD_LOGIC;
    localMac : in STD_LOGIC_VECTOR ( 47 downto 0 );
    localIp : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ethLinkUp : out STD_LOGIC;
    \timingReadMaster[araddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingReadMaster[arprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \timingReadMaster[arvalid]\ : in STD_LOGIC;
    \timingReadMaster[rready]\ : in STD_LOGIC;
    \timingReadSlave[arready]\ : out STD_LOGIC;
    \timingReadSlave[rdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingReadSlave[rresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingReadSlave[rvalid]\ : out STD_LOGIC;
    \timingWriteMaster[awaddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingWriteMaster[awprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \timingWriteMaster[awvalid]\ : in STD_LOGIC;
    \timingWriteMaster[wdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \timingWriteMaster[wstrb]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \timingWriteMaster[wvalid]\ : in STD_LOGIC;
    \timingWriteMaster[bready]\ : in STD_LOGIC;
    \timingWriteSlave[awready]\ : out STD_LOGIC;
    \timingWriteSlave[wready]\ : out STD_LOGIC;
    \timingWriteSlave[bresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \timingWriteSlave[bvalid]\ : out STD_LOGIC;
    \bsaReadMaster[araddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \bsaReadMaster[arprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \bsaReadMaster[arvalid]\ : in STD_LOGIC;
    \bsaReadMaster[rready]\ : in STD_LOGIC;
    \bsaReadSlave[arready]\ : out STD_LOGIC;
    \bsaReadSlave[rdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \bsaReadSlave[rresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \bsaReadSlave[rvalid]\ : out STD_LOGIC;
    \bsaWriteMaster[awaddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \bsaWriteMaster[awprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \bsaWriteMaster[awvalid]\ : in STD_LOGIC;
    \bsaWriteMaster[wdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \bsaWriteMaster[wstrb]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \bsaWriteMaster[wvalid]\ : in STD_LOGIC;
    \bsaWriteMaster[bready]\ : in STD_LOGIC;
    \bsaWriteSlave[awready]\ : out STD_LOGIC;
    \bsaWriteSlave[wready]\ : out STD_LOGIC;
    \bsaWriteSlave[bresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \bsaWriteSlave[bvalid]\ : out STD_LOGIC;
    \ddrReadMaster[araddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ddrReadMaster[arprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \ddrReadMaster[arvalid]\ : in STD_LOGIC;
    \ddrReadMaster[rready]\ : in STD_LOGIC;
    \ddrReadSlave[arready]\ : out STD_LOGIC;
    \ddrReadSlave[rdata]\ : out STD_LOGIC_VECTOR ( 31 downto 0 );
    \ddrReadSlave[rresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \ddrReadSlave[rvalid]\ : out STD_LOGIC;
    \ddrWriteMaster[awaddr]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ddrWriteMaster[awprot]\ : in STD_LOGIC_VECTOR ( 2 downto 0 );
    \ddrWriteMaster[awvalid]\ : in STD_LOGIC;
    \ddrWriteMaster[wdata]\ : in STD_LOGIC_VECTOR ( 31 downto 0 );
    \ddrWriteMaster[wstrb]\ : in STD_LOGIC_VECTOR ( 3 downto 0 );
    \ddrWriteMaster[wvalid]\ : in STD_LOGIC;
    \ddrWriteMaster[bready]\ : in STD_LOGIC;
    \ddrWriteSlave[awready]\ : out STD_LOGIC;
    \ddrWriteSlave[wready]\ : out STD_LOGIC;
    \ddrWriteSlave[bresp]\ : out STD_LOGIC_VECTOR ( 1 downto 0 );
    \ddrWriteSlave[bvalid]\ : out STD_LOGIC;
    ddrMemReady : out STD_LOGIC;
    ddrMemError : out STD_LOGIC;
    fabClkP : in STD_LOGIC;
    fabClkN : in STD_LOGIC;
    ethRxP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ethRxN : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ethTxP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ethTxN : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ethClkP : in STD_LOGIC;
    ethClkN : in STD_LOGIC;
    timingRxP : in STD_LOGIC;
    timingRxN : in STD_LOGIC;
    timingTxP : out STD_LOGIC;
    timingTxN : out STD_LOGIC;
    timingRefClkInP : in STD_LOGIC;
    timingRefClkInN : in STD_LOGIC;
    timingRecClkOutP : out STD_LOGIC;
    timingRecClkOutN : out STD_LOGIC;
    timingClkSel : out STD_LOGIC;
    enAuxPwrL : out STD_LOGIC;
    ddrClkP : in STD_LOGIC;
    ddrClkN : in STD_LOGIC;
    ddrDm : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ddrDqsP : inout STD_LOGIC_VECTOR ( 7 downto 0 );
    ddrDqsN : inout STD_LOGIC_VECTOR ( 7 downto 0 );
    ddrDq : inout STD_LOGIC_VECTOR ( 63 downto 0 );
    ddrA : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ddrBa : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ddrCsL : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ddrOdt : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ddrCke : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ddrCkP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ddrCkN : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ddrWeL : out STD_LOGIC;
    ddrRasL : out STD_LOGIC;
    ddrCasL : out STD_LOGIC;
    ddrRstL : out STD_LOGIC;
    ddrAlertL : in STD_LOGIC;
    ddrPg : in STD_LOGIC;
    ddrPwrEnL : out STD_LOGIC
  );

end AmcCarrierCore;

architecture stub of AmcCarrierCore is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "timingClk,timingRst,\timingBusIntf[strobe]\,\timingBusIntf[valid]\,\timingBusIntf[message][version]\[15:0],\timingBusIntf[message][pulseId]\[63:0],\timingBusIntf[message][timeStamp]\[63:0],\timingBusIntf[message][fixedRates]\[9:0],\timingBusIntf[message][acRates]\[5:0],\timingBusIntf[message][acTimeSlot]\[2:0],\timingBusIntf[message][acTimeSlotPhase]\[11:0],\timingBusIntf[message][resync]\,\timingBusIntf[message][beamRequest]\[31:0],\timingBusIntf[message][beamEnergy][0]\[15:0],\timingBusIntf[message][beamEnergy][1]\[15:0],\timingBusIntf[message][beamEnergy][2]\[15:0],\timingBusIntf[message][beamEnergy][3]\[15:0],\timingBusIntf[message][photonWavelen][0]\[15:0],\timingBusIntf[message][photonWavelen][1]\[15:0],\timingBusIntf[message][syncStatus]\,\timingBusIntf[message][mpsValid]\,\timingBusIntf[message][bcsFault]\[0:0],\timingBusIntf[message][mpsLimit]\[15:0],\timingBusIntf[message][mpsClass][0]\[3:0],\timingBusIntf[message][mpsClass][1]\[3:0],\timingBusIntf[message][mpsClass][2]\[3:0],\timingBusIntf[message][mpsClass][3]\[3:0],\timingBusIntf[message][mpsClass][4]\[3:0],\timingBusIntf[message][mpsClass][5]\[3:0],\timingBusIntf[message][mpsClass][6]\[3:0],\timingBusIntf[message][mpsClass][7]\[3:0],\timingBusIntf[message][mpsClass][8]\[3:0],\timingBusIntf[message][mpsClass][9]\[3:0],\timingBusIntf[message][mpsClass][10]\[3:0],\timingBusIntf[message][mpsClass][11]\[3:0],\timingBusIntf[message][mpsClass][12]\[3:0],\timingBusIntf[message][mpsClass][13]\[3:0],\timingBusIntf[message][mpsClass][14]\[3:0],\timingBusIntf[message][mpsClass][15]\[3:0],\timingBusIntf[message][bsaInit]\[63:0],\timingBusIntf[message][bsaActive]\[63:0],\timingBusIntf[message][bsaAvgDone]\[63:0],\timingBusIntf[message][bsaDone]\[63:0],\timingBusIntf[message][control][0]\[15:0],\timingBusIntf[message][control][1]\[15:0],\timingBusIntf[message][control][2]\[15:0],\timingBusIntf[message][control][3]\[15:0],\timingBusIntf[message][control][4]\[15:0],\timingBusIntf[message][control][5]\[15:0],\timingBusIntf[message][control][6]\[15:0],\timingBusIntf[message][control][7]\[15:0],\timingBusIntf[message][control][8]\[15:0],\timingBusIntf[message][control][9]\[15:0],\timingBusIntf[message][control][10]\[15:0],\timingBusIntf[message][control][11]\[15:0],\timingBusIntf[message][control][12]\[15:0],\timingBusIntf[message][control][13]\[15:0],\timingBusIntf[message][control][14]\[15:0],\timingBusIntf[message][control][15]\[15:0],\timingBusIntf[message][control][16]\[15:0],\timingBusIntf[message][control][17]\[15:0],\timingBusIntf[stream][pulseId]\[31:0],\timingBusIntf[stream][eventCodes]\[255:0],\timingBusIntf[stream][dbuff][dtype]\[15:0],\timingBusIntf[stream][dbuff][version]\[15:0],\timingBusIntf[stream][dbuff][dmod]\[191:0],\timingBusIntf[stream][dbuff][epicsTime]\[63:0],\timingBusIntf[stream][dbuff][edefAvgDn]\[31:0],\timingBusIntf[stream][dbuff][edefMinor]\[31:0],\timingBusIntf[stream][dbuff][edefMajor]\[31:0],\timingBusIntf[stream][dbuff][edefInit]\[31:0],\timingBusIntf[v1][linkUp]\,\timingBusIntf[v1][gtRxData]\[15:0],\timingBusIntf[v1][gtRxDataK]\[1:0],\timingBusIntf[v1][gtRxDispErr]\[1:0],\timingBusIntf[v1][gtRxDecErr]\[1:0],\timingBusIntf[v2][linkUp]\,\timingPhy[dataK]\[1:0],\timingPhy[data]\[15:0],\timingPhy[control][reset]\,\timingPhy[control][inhibit]\,\timingPhy[control][polarity]\,\timingPhy[control][bufferByRst]\,\timingPhy[control][pllReset]\,timingPhyClk,timingPhyRst,timingRefClk,timingRefClkDiv2,diagnosticClk,diagnosticRst,\diagnosticBus[strobe]\,\diagnosticBus[data][31]\[31:0],\diagnosticBus[data][30]\[31:0],\diagnosticBus[data][29]\[31:0],\diagnosticBus[data][28]\[31:0],\diagnosticBus[data][27]\[31:0],\diagnosticBus[data][26]\[31:0],\diagnosticBus[data][25]\[31:0],\diagnosticBus[data][24]\[31:0],\diagnosticBus[data][23]\[31:0],\diagnosticBus[data][22]\[31:0],\diagnosticBus[data][21]\[31:0],\diagnosticBus[data][20]\[31:0],\diagnosticBus[data][19]\[31:0],\diagnosticBus[data][18]\[31:0],\diagnosticBus[data][17]\[31:0],\diagnosticBus[data][16]\[31:0],\diagnosticBus[data][15]\[31:0],\diagnosticBus[data][14]\[31:0],\diagnosticBus[data][13]\[31:0],\diagnosticBus[data][12]\[31:0],\diagnosticBus[data][11]\[31:0],\diagnosticBus[data][10]\[31:0],\diagnosticBus[data][9]\[31:0],\diagnosticBus[data][8]\[31:0],\diagnosticBus[data][7]\[31:0],\diagnosticBus[data][6]\[31:0],\diagnosticBus[data][5]\[31:0],\diagnosticBus[data][4]\[31:0],\diagnosticBus[data][3]\[31:0],\diagnosticBus[data][2]\[31:0],\diagnosticBus[data][1]\[31:0],\diagnosticBus[data][0]\[31:0],\diagnosticBus[sevr][31]\[1:0],\diagnosticBus[sevr][30]\[1:0],\diagnosticBus[sevr][29]\[1:0],\diagnosticBus[sevr][28]\[1:0],\diagnosticBus[sevr][27]\[1:0],\diagnosticBus[sevr][26]\[1:0],\diagnosticBus[sevr][25]\[1:0],\diagnosticBus[sevr][24]\[1:0],\diagnosticBus[sevr][23]\[1:0],\diagnosticBus[sevr][22]\[1:0],\diagnosticBus[sevr][21]\[1:0],\diagnosticBus[sevr][20]\[1:0],\diagnosticBus[sevr][19]\[1:0],\diagnosticBus[sevr][18]\[1:0],\diagnosticBus[sevr][17]\[1:0],\diagnosticBus[sevr][16]\[1:0],\diagnosticBus[sevr][15]\[1:0],\diagnosticBus[sevr][14]\[1:0],\diagnosticBus[sevr][13]\[1:0],\diagnosticBus[sevr][12]\[1:0],\diagnosticBus[sevr][11]\[1:0],\diagnosticBus[sevr][10]\[1:0],\diagnosticBus[sevr][9]\[1:0],\diagnosticBus[sevr][8]\[1:0],\diagnosticBus[sevr][7]\[1:0],\diagnosticBus[sevr][6]\[1:0],\diagnosticBus[sevr][5]\[1:0],\diagnosticBus[sevr][4]\[1:0],\diagnosticBus[sevr][3]\[1:0],\diagnosticBus[sevr][2]\[1:0],\diagnosticBus[sevr][1]\[1:0],\diagnosticBus[sevr][0]\[1:0],\diagnosticBus[fixed]\[31:0],\diagnosticBus[mpsIgnore]\[31:0],\diagnosticBus[timingMessage][version]\[15:0],\diagnosticBus[timingMessage][pulseId]\[63:0],\diagnosticBus[timingMessage][timeStamp]\[63:0],\diagnosticBus[timingMessage][fixedRates]\[9:0],\diagnosticBus[timingMessage][acRates]\[5:0],\diagnosticBus[timingMessage][acTimeSlot]\[2:0],\diagnosticBus[timingMessage][acTimeSlotPhase]\[11:0],\diagnosticBus[timingMessage][resync]\,\diagnosticBus[timingMessage][beamRequest]\[31:0],\diagnosticBus[timingMessage][beamEnergy][0]\[15:0],\diagnosticBus[timingMessage][beamEnergy][1]\[15:0],\diagnosticBus[timingMessage][beamEnergy][2]\[15:0],\diagnosticBus[timingMessage][beamEnergy][3]\[15:0],\diagnosticBus[timingMessage][photonWavelen][0]\[15:0],\diagnosticBus[timingMessage][photonWavelen][1]\[15:0],\diagnosticBus[timingMessage][syncStatus]\,\diagnosticBus[timingMessage][mpsValid]\,\diagnosticBus[timingMessage][bcsFault]\[0:0],\diagnosticBus[timingMessage][mpsLimit]\[15:0],\diagnosticBus[timingMessage][mpsClass][0]\[3:0],\diagnosticBus[timingMessage][mpsClass][1]\[3:0],\diagnosticBus[timingMessage][mpsClass][2]\[3:0],\diagnosticBus[timingMessage][mpsClass][3]\[3:0],\diagnosticBus[timingMessage][mpsClass][4]\[3:0],\diagnosticBus[timingMessage][mpsClass][5]\[3:0],\diagnosticBus[timingMessage][mpsClass][6]\[3:0],\diagnosticBus[timingMessage][mpsClass][7]\[3:0],\diagnosticBus[timingMessage][mpsClass][8]\[3:0],\diagnosticBus[timingMessage][mpsClass][9]\[3:0],\diagnosticBus[timingMessage][mpsClass][10]\[3:0],\diagnosticBus[timingMessage][mpsClass][11]\[3:0],\diagnosticBus[timingMessage][mpsClass][12]\[3:0],\diagnosticBus[timingMessage][mpsClass][13]\[3:0],\diagnosticBus[timingMessage][mpsClass][14]\[3:0],\diagnosticBus[timingMessage][mpsClass][15]\[3:0],\diagnosticBus[timingMessage][bsaInit]\[63:0],\diagnosticBus[timingMessage][bsaActive]\[63:0],\diagnosticBus[timingMessage][bsaAvgDone]\[63:0],\diagnosticBus[timingMessage][bsaDone]\[63:0],\diagnosticBus[timingMessage][control][0]\[15:0],\diagnosticBus[timingMessage][control][1]\[15:0],\diagnosticBus[timingMessage][control][2]\[15:0],\diagnosticBus[timingMessage][control][3]\[15:0],\diagnosticBus[timingMessage][control][4]\[15:0],\diagnosticBus[timingMessage][control][5]\[15:0],\diagnosticBus[timingMessage][control][6]\[15:0],\diagnosticBus[timingMessage][control][7]\[15:0],\diagnosticBus[timingMessage][control][8]\[15:0],\diagnosticBus[timingMessage][control][9]\[15:0],\diagnosticBus[timingMessage][control][10]\[15:0],\diagnosticBus[timingMessage][control][11]\[15:0],\diagnosticBus[timingMessage][control][12]\[15:0],\diagnosticBus[timingMessage][control][13]\[15:0],\diagnosticBus[timingMessage][control][14]\[15:0],\diagnosticBus[timingMessage][control][15]\[15:0],\diagnosticBus[timingMessage][control][16]\[15:0],\diagnosticBus[timingMessage][control][17]\[15:0],waveformClk,waveformRst,\obAppWaveformMasters[1][3][tValid]\,\obAppWaveformMasters[1][3][tData]\[127:0],\obAppWaveformMasters[1][3][tStrb]\[15:0],\obAppWaveformMasters[1][3][tKeep]\[15:0],\obAppWaveformMasters[1][3][tLast]\,\obAppWaveformMasters[1][3][tDest]\[7:0],\obAppWaveformMasters[1][3][tId]\[7:0],\obAppWaveformMasters[1][3][tUser]\[127:0],\obAppWaveformMasters[1][2][tValid]\,\obAppWaveformMasters[1][2][tData]\[127:0],\obAppWaveformMasters[1][2][tStrb]\[15:0],\obAppWaveformMasters[1][2][tKeep]\[15:0],\obAppWaveformMasters[1][2][tLast]\,\obAppWaveformMasters[1][2][tDest]\[7:0],\obAppWaveformMasters[1][2][tId]\[7:0],\obAppWaveformMasters[1][2][tUser]\[127:0],\obAppWaveformMasters[1][1][tValid]\,\obAppWaveformMasters[1][1][tData]\[127:0],\obAppWaveformMasters[1][1][tStrb]\[15:0],\obAppWaveformMasters[1][1][tKeep]\[15:0],\obAppWaveformMasters[1][1][tLast]\,\obAppWaveformMasters[1][1][tDest]\[7:0],\obAppWaveformMasters[1][1][tId]\[7:0],\obAppWaveformMasters[1][1][tUser]\[127:0],\obAppWaveformMasters[1][0][tValid]\,\obAppWaveformMasters[1][0][tData]\[127:0],\obAppWaveformMasters[1][0][tStrb]\[15:0],\obAppWaveformMasters[1][0][tKeep]\[15:0],\obAppWaveformMasters[1][0][tLast]\,\obAppWaveformMasters[1][0][tDest]\[7:0],\obAppWaveformMasters[1][0][tId]\[7:0],\obAppWaveformMasters[1][0][tUser]\[127:0],\obAppWaveformMasters[0][3][tValid]\,\obAppWaveformMasters[0][3][tData]\[127:0],\obAppWaveformMasters[0][3][tStrb]\[15:0],\obAppWaveformMasters[0][3][tKeep]\[15:0],\obAppWaveformMasters[0][3][tLast]\,\obAppWaveformMasters[0][3][tDest]\[7:0],\obAppWaveformMasters[0][3][tId]\[7:0],\obAppWaveformMasters[0][3][tUser]\[127:0],\obAppWaveformMasters[0][2][tValid]\,\obAppWaveformMasters[0][2][tData]\[127:0],\obAppWaveformMasters[0][2][tStrb]\[15:0],\obAppWaveformMasters[0][2][tKeep]\[15:0],\obAppWaveformMasters[0][2][tLast]\,\obAppWaveformMasters[0][2][tDest]\[7:0],\obAppWaveformMasters[0][2][tId]\[7:0],\obAppWaveformMasters[0][2][tUser]\[127:0],\obAppWaveformMasters[0][1][tValid]\,\obAppWaveformMasters[0][1][tData]\[127:0],\obAppWaveformMasters[0][1][tStrb]\[15:0],\obAppWaveformMasters[0][1][tKeep]\[15:0],\obAppWaveformMasters[0][1][tLast]\,\obAppWaveformMasters[0][1][tDest]\[7:0],\obAppWaveformMasters[0][1][tId]\[7:0],\obAppWaveformMasters[0][1][tUser]\[127:0],\obAppWaveformMasters[0][0][tValid]\,\obAppWaveformMasters[0][0][tData]\[127:0],\obAppWaveformMasters[0][0][tStrb]\[15:0],\obAppWaveformMasters[0][0][tKeep]\[15:0],\obAppWaveformMasters[0][0][tLast]\,\obAppWaveformMasters[0][0][tDest]\[7:0],\obAppWaveformMasters[0][0][tId]\[7:0],\obAppWaveformMasters[0][0][tUser]\[127:0],\obAppWaveformSlaves[1][3][slave][tReady]\,\obAppWaveformSlaves[1][3][ctrl][pause]\,\obAppWaveformSlaves[1][3][ctrl][overflow]\,\obAppWaveformSlaves[1][3][ctrl][idle]\,\obAppWaveformSlaves[1][2][slave][tReady]\,\obAppWaveformSlaves[1][2][ctrl][pause]\,\obAppWaveformSlaves[1][2][ctrl][overflow]\,\obAppWaveformSlaves[1][2][ctrl][idle]\,\obAppWaveformSlaves[1][1][slave][tReady]\,\obAppWaveformSlaves[1][1][ctrl][pause]\,\obAppWaveformSlaves[1][1][ctrl][overflow]\,\obAppWaveformSlaves[1][1][ctrl][idle]\,\obAppWaveformSlaves[1][0][slave][tReady]\,\obAppWaveformSlaves[1][0][ctrl][pause]\,\obAppWaveformSlaves[1][0][ctrl][overflow]\,\obAppWaveformSlaves[1][0][ctrl][idle]\,\obAppWaveformSlaves[0][3][slave][tReady]\,\obAppWaveformSlaves[0][3][ctrl][pause]\,\obAppWaveformSlaves[0][3][ctrl][overflow]\,\obAppWaveformSlaves[0][3][ctrl][idle]\,\obAppWaveformSlaves[0][2][slave][tReady]\,\obAppWaveformSlaves[0][2][ctrl][pause]\,\obAppWaveformSlaves[0][2][ctrl][overflow]\,\obAppWaveformSlaves[0][2][ctrl][idle]\,\obAppWaveformSlaves[0][1][slave][tReady]\,\obAppWaveformSlaves[0][1][ctrl][pause]\,\obAppWaveformSlaves[0][1][ctrl][overflow]\,\obAppWaveformSlaves[0][1][ctrl][idle]\,\obAppWaveformSlaves[0][0][slave][tReady]\,\obAppWaveformSlaves[0][0][ctrl][pause]\,\obAppWaveformSlaves[0][0][ctrl][overflow]\,\obAppWaveformSlaves[0][0][ctrl][idle]\,\ibAppWaveformMasters[1][3][tValid]\,\ibAppWaveformMasters[1][3][tData]\[127:0],\ibAppWaveformMasters[1][3][tStrb]\[15:0],\ibAppWaveformMasters[1][3][tKeep]\[15:0],\ibAppWaveformMasters[1][3][tLast]\,\ibAppWaveformMasters[1][3][tDest]\[7:0],\ibAppWaveformMasters[1][3][tId]\[7:0],\ibAppWaveformMasters[1][3][tUser]\[127:0],\ibAppWaveformMasters[1][2][tValid]\,\ibAppWaveformMasters[1][2][tData]\[127:0],\ibAppWaveformMasters[1][2][tStrb]\[15:0],\ibAppWaveformMasters[1][2][tKeep]\[15:0],\ibAppWaveformMasters[1][2][tLast]\,\ibAppWaveformMasters[1][2][tDest]\[7:0],\ibAppWaveformMasters[1][2][tId]\[7:0],\ibAppWaveformMasters[1][2][tUser]\[127:0],\ibAppWaveformMasters[1][1][tValid]\,\ibAppWaveformMasters[1][1][tData]\[127:0],\ibAppWaveformMasters[1][1][tStrb]\[15:0],\ibAppWaveformMasters[1][1][tKeep]\[15:0],\ibAppWaveformMasters[1][1][tLast]\,\ibAppWaveformMasters[1][1][tDest]\[7:0],\ibAppWaveformMasters[1][1][tId]\[7:0],\ibAppWaveformMasters[1][1][tUser]\[127:0],\ibAppWaveformMasters[1][0][tValid]\,\ibAppWaveformMasters[1][0][tData]\[127:0],\ibAppWaveformMasters[1][0][tStrb]\[15:0],\ibAppWaveformMasters[1][0][tKeep]\[15:0],\ibAppWaveformMasters[1][0][tLast]\,\ibAppWaveformMasters[1][0][tDest]\[7:0],\ibAppWaveformMasters[1][0][tId]\[7:0],\ibAppWaveformMasters[1][0][tUser]\[127:0],\ibAppWaveformMasters[0][3][tValid]\,\ibAppWaveformMasters[0][3][tData]\[127:0],\ibAppWaveformMasters[0][3][tStrb]\[15:0],\ibAppWaveformMasters[0][3][tKeep]\[15:0],\ibAppWaveformMasters[0][3][tLast]\,\ibAppWaveformMasters[0][3][tDest]\[7:0],\ibAppWaveformMasters[0][3][tId]\[7:0],\ibAppWaveformMasters[0][3][tUser]\[127:0],\ibAppWaveformMasters[0][2][tValid]\,\ibAppWaveformMasters[0][2][tData]\[127:0],\ibAppWaveformMasters[0][2][tStrb]\[15:0],\ibAppWaveformMasters[0][2][tKeep]\[15:0],\ibAppWaveformMasters[0][2][tLast]\,\ibAppWaveformMasters[0][2][tDest]\[7:0],\ibAppWaveformMasters[0][2][tId]\[7:0],\ibAppWaveformMasters[0][2][tUser]\[127:0],\ibAppWaveformMasters[0][1][tValid]\,\ibAppWaveformMasters[0][1][tData]\[127:0],\ibAppWaveformMasters[0][1][tStrb]\[15:0],\ibAppWaveformMasters[0][1][tKeep]\[15:0],\ibAppWaveformMasters[0][1][tLast]\,\ibAppWaveformMasters[0][1][tDest]\[7:0],\ibAppWaveformMasters[0][1][tId]\[7:0],\ibAppWaveformMasters[0][1][tUser]\[127:0],\ibAppWaveformMasters[0][0][tValid]\,\ibAppWaveformMasters[0][0][tData]\[127:0],\ibAppWaveformMasters[0][0][tStrb]\[15:0],\ibAppWaveformMasters[0][0][tKeep]\[15:0],\ibAppWaveformMasters[0][0][tLast]\,\ibAppWaveformMasters[0][0][tDest]\[7:0],\ibAppWaveformMasters[0][0][tId]\[7:0],\ibAppWaveformMasters[0][0][tUser]\[127:0],\ibAppWaveformSlaves[1][3][slave][tReady]\,\ibAppWaveformSlaves[1][3][ctrl][pause]\,\ibAppWaveformSlaves[1][3][ctrl][overflow]\,\ibAppWaveformSlaves[1][3][ctrl][idle]\,\ibAppWaveformSlaves[1][2][slave][tReady]\,\ibAppWaveformSlaves[1][2][ctrl][pause]\,\ibAppWaveformSlaves[1][2][ctrl][overflow]\,\ibAppWaveformSlaves[1][2][ctrl][idle]\,\ibAppWaveformSlaves[1][1][slave][tReady]\,\ibAppWaveformSlaves[1][1][ctrl][pause]\,\ibAppWaveformSlaves[1][1][ctrl][overflow]\,\ibAppWaveformSlaves[1][1][ctrl][idle]\,\ibAppWaveformSlaves[1][0][slave][tReady]\,\ibAppWaveformSlaves[1][0][ctrl][pause]\,\ibAppWaveformSlaves[1][0][ctrl][overflow]\,\ibAppWaveformSlaves[1][0][ctrl][idle]\,\ibAppWaveformSlaves[0][3][slave][tReady]\,\ibAppWaveformSlaves[0][3][ctrl][pause]\,\ibAppWaveformSlaves[0][3][ctrl][overflow]\,\ibAppWaveformSlaves[0][3][ctrl][idle]\,\ibAppWaveformSlaves[0][2][slave][tReady]\,\ibAppWaveformSlaves[0][2][ctrl][pause]\,\ibAppWaveformSlaves[0][2][ctrl][overflow]\,\ibAppWaveformSlaves[0][2][ctrl][idle]\,\ibAppWaveformSlaves[0][1][slave][tReady]\,\ibAppWaveformSlaves[0][1][ctrl][pause]\,\ibAppWaveformSlaves[0][1][ctrl][overflow]\,\ibAppWaveformSlaves[0][1][ctrl][idle]\,\ibAppWaveformSlaves[0][0][slave][tReady]\,\ibAppWaveformSlaves[0][0][ctrl][pause]\,\ibAppWaveformSlaves[0][0][ctrl][overflow]\,\ibAppWaveformSlaves[0][0][ctrl][idle]\,\obBpMsgClientMaster[tValid]\,\obBpMsgClientMaster[tData]\[127:0],\obBpMsgClientMaster[tStrb]\[15:0],\obBpMsgClientMaster[tKeep]\[15:0],\obBpMsgClientMaster[tLast]\,\obBpMsgClientMaster[tDest]\[7:0],\obBpMsgClientMaster[tId]\[7:0],\obBpMsgClientMaster[tUser]\[127:0],\obBpMsgClientSlave[tReady]\,\ibBpMsgClientMaster[tValid]\,\ibBpMsgClientMaster[tData]\[127:0],\ibBpMsgClientMaster[tStrb]\[15:0],\ibBpMsgClientMaster[tKeep]\[15:0],\ibBpMsgClientMaster[tLast]\,\ibBpMsgClientMaster[tDest]\[7:0],\ibBpMsgClientMaster[tId]\[7:0],\ibBpMsgClientMaster[tUser]\[127:0],\ibBpMsgClientSlave[tReady]\,\obBpMsgServerMaster[tValid]\,\obBpMsgServerMaster[tData]\[127:0],\obBpMsgServerMaster[tStrb]\[15:0],\obBpMsgServerMaster[tKeep]\[15:0],\obBpMsgServerMaster[tLast]\,\obBpMsgServerMaster[tDest]\[7:0],\obBpMsgServerMaster[tId]\[7:0],\obBpMsgServerMaster[tUser]\[127:0],\obBpMsgServerSlave[tReady]\,\ibBpMsgServerMaster[tValid]\,\ibBpMsgServerMaster[tData]\[127:0],\ibBpMsgServerMaster[tStrb]\[15:0],\ibBpMsgServerMaster[tKeep]\[15:0],\ibBpMsgServerMaster[tLast]\,\ibBpMsgServerMaster[tDest]\[7:0],\ibBpMsgServerMaster[tId]\[7:0],\ibBpMsgServerMaster[tUser]\[127:0],\ibBpMsgServerSlave[tReady]\,\obAppDebugMaster[tValid]\,\obAppDebugMaster[tData]\[127:0],\obAppDebugMaster[tStrb]\[15:0],\obAppDebugMaster[tKeep]\[15:0],\obAppDebugMaster[tLast]\,\obAppDebugMaster[tDest]\[7:0],\obAppDebugMaster[tId]\[7:0],\obAppDebugMaster[tUser]\[127:0],\obAppDebugSlave[tReady]\,\ibAppDebugMaster[tValid]\,\ibAppDebugMaster[tData]\[127:0],\ibAppDebugMaster[tStrb]\[15:0],\ibAppDebugMaster[tKeep]\[15:0],\ibAppDebugMaster[tLast]\,\ibAppDebugMaster[tDest]\[7:0],\ibAppDebugMaster[tId]\[7:0],\ibAppDebugMaster[tUser]\[127:0],\ibAppDebugSlave[tReady]\,recTimingClk,recTimingRst,ref156MHzClk,ref156MHzRst,gthFabClk,\axilReadMasters[1][araddr]\[31:0],\axilReadMasters[1][arprot]\[2:0],\axilReadMasters[1][arvalid]\,\axilReadMasters[1][rready]\,\axilReadMasters[0][araddr]\[31:0],\axilReadMasters[0][arprot]\[2:0],\axilReadMasters[0][arvalid]\,\axilReadMasters[0][rready]\,\axilReadSlaves[1][arready]\,\axilReadSlaves[1][rdata]\[31:0],\axilReadSlaves[1][rresp]\[1:0],\axilReadSlaves[1][rvalid]\,\axilReadSlaves[0][arready]\,\axilReadSlaves[0][rdata]\[31:0],\axilReadSlaves[0][rresp]\[1:0],\axilReadSlaves[0][rvalid]\,\axilWriteMasters[1][awaddr]\[31:0],\axilWriteMasters[1][awprot]\[2:0],\axilWriteMasters[1][awvalid]\,\axilWriteMasters[1][wdata]\[31:0],\axilWriteMasters[1][wstrb]\[3:0],\axilWriteMasters[1][wvalid]\,\axilWriteMasters[1][bready]\,\axilWriteMasters[0][awaddr]\[31:0],\axilWriteMasters[0][awprot]\[2:0],\axilWriteMasters[0][awvalid]\,\axilWriteMasters[0][wdata]\[31:0],\axilWriteMasters[0][wstrb]\[3:0],\axilWriteMasters[0][wvalid]\,\axilWriteMasters[0][bready]\,\axilWriteSlaves[1][awready]\,\axilWriteSlaves[1][wready]\,\axilWriteSlaves[1][bresp]\[1:0],\axilWriteSlaves[1][bvalid]\,\axilWriteSlaves[0][awready]\,\axilWriteSlaves[0][wready]\,\axilWriteSlaves[0][bresp]\[1:0],\axilWriteSlaves[0][bvalid]\,\ethReadMaster[araddr]\[31:0],\ethReadMaster[arprot]\[2:0],\ethReadMaster[arvalid]\,\ethReadMaster[rready]\,\ethReadSlave[arready]\,\ethReadSlave[rdata]\[31:0],\ethReadSlave[rresp]\[1:0],\ethReadSlave[rvalid]\,\ethWriteMaster[awaddr]\[31:0],\ethWriteMaster[awprot]\[2:0],\ethWriteMaster[awvalid]\,\ethWriteMaster[wdata]\[31:0],\ethWriteMaster[wstrb]\[3:0],\ethWriteMaster[wvalid]\,\ethWriteMaster[bready]\,\ethWriteSlave[awready]\,\ethWriteSlave[wready]\,\ethWriteSlave[bresp]\[1:0],\ethWriteSlave[bvalid]\,localMac[47:0],localIp[31:0],ethLinkUp,\timingReadMaster[araddr]\[31:0],\timingReadMaster[arprot]\[2:0],\timingReadMaster[arvalid]\,\timingReadMaster[rready]\,\timingReadSlave[arready]\,\timingReadSlave[rdata]\[31:0],\timingReadSlave[rresp]\[1:0],\timingReadSlave[rvalid]\,\timingWriteMaster[awaddr]\[31:0],\timingWriteMaster[awprot]\[2:0],\timingWriteMaster[awvalid]\,\timingWriteMaster[wdata]\[31:0],\timingWriteMaster[wstrb]\[3:0],\timingWriteMaster[wvalid]\,\timingWriteMaster[bready]\,\timingWriteSlave[awready]\,\timingWriteSlave[wready]\,\timingWriteSlave[bresp]\[1:0],\timingWriteSlave[bvalid]\,\bsaReadMaster[araddr]\[31:0],\bsaReadMaster[arprot]\[2:0],\bsaReadMaster[arvalid]\,\bsaReadMaster[rready]\,\bsaReadSlave[arready]\,\bsaReadSlave[rdata]\[31:0],\bsaReadSlave[rresp]\[1:0],\bsaReadSlave[rvalid]\,\bsaWriteMaster[awaddr]\[31:0],\bsaWriteMaster[awprot]\[2:0],\bsaWriteMaster[awvalid]\,\bsaWriteMaster[wdata]\[31:0],\bsaWriteMaster[wstrb]\[3:0],\bsaWriteMaster[wvalid]\,\bsaWriteMaster[bready]\,\bsaWriteSlave[awready]\,\bsaWriteSlave[wready]\,\bsaWriteSlave[bresp]\[1:0],\bsaWriteSlave[bvalid]\,\ddrReadMaster[araddr]\[31:0],\ddrReadMaster[arprot]\[2:0],\ddrReadMaster[arvalid]\,\ddrReadMaster[rready]\,\ddrReadSlave[arready]\,\ddrReadSlave[rdata]\[31:0],\ddrReadSlave[rresp]\[1:0],\ddrReadSlave[rvalid]\,\ddrWriteMaster[awaddr]\[31:0],\ddrWriteMaster[awprot]\[2:0],\ddrWriteMaster[awvalid]\,\ddrWriteMaster[wdata]\[31:0],\ddrWriteMaster[wstrb]\[3:0],\ddrWriteMaster[wvalid]\,\ddrWriteMaster[bready]\,\ddrWriteSlave[awready]\,\ddrWriteSlave[wready]\,\ddrWriteSlave[bresp]\[1:0],\ddrWriteSlave[bvalid]\,ddrMemReady,ddrMemError,fabClkP,fabClkN,ethRxP[3:0],ethRxN[3:0],ethTxP[3:0],ethTxN[3:0],ethClkP,ethClkN,timingRxP,timingRxN,timingTxP,timingTxN,timingRefClkInP,timingRefClkInN,timingRecClkOutP,timingRecClkOutN,timingClkSel,enAuxPwrL,ddrClkP,ddrClkN,ddrDm[7:0],ddrDqsP[7:0],ddrDqsN[7:0],ddrDq[63:0],ddrA[15:0],ddrBa[2:0],ddrCsL[1:0],ddrOdt[1:0],ddrCke[1:0],ddrCkP[1:0],ddrCkN[1:0],ddrWeL,ddrRasL,ddrCasL,ddrRstL,ddrAlertL,ddrPg,ddrPwrEnL";
begin
end;
