# ----------------------------------------------------------------------------
# Title      : AMC Carrier Core GitHub Actions CI Script
# ----------------------------------------------------------------------------
# This file is part of the 'AMC Carrier Core library'. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the 'AMC Carrier Core library', including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------
# The following environment variables are required for this process:
# secrets.GH_TOKEN
# secrets.CONDA_UPLOAD_TOKEN_TAG

name: AMC Carrier Core Integration
on: [push]

jobs:

  test_and_document:
    name: Test And Generate Documentation
    runs-on: ubuntu-24.04
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz ghdl
          python -m pip install --upgrade pip
          pip install flake8

      - name: Check for trailing whitespace
        run: |
          if grep -rnI '[[:blank:]]$' --include=\*.{vhd,v,tcl,py,yaml,xdc} .; then
            echo "Error: Trailing whitespace found in the repository!"
            exit 1
          fi

      - name: VHDL Syntax Check
        run: |
          make
          rm -rf ghdl-build

      - name: Python Syntax Check
        run: |
          python -m compileall -f python/
          flake8 --count python/

      - name: Generate Documentation
        run: |
          doxygen Doxyfile

      - name: Deploy Documentation
        if: startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: doxygen/html

# ----------------------------------------------------------------------------

  gen_release:
    needs: [test_and_document]
    uses: slaclab/ruckus/.github/workflows/gen_release.yml@main
    with:
      version: '1.0.0'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

# ----------------------------------------------------------------------------

  conda_build_lib:
    needs: [test_and_document]
    uses: slaclab/ruckus/.github/workflows/conda_build_lib.yml@main
    with:
      version: '1.0.0'
    secrets:
      CONDA_UPLOAD_TOKEN_TAG: ${{ secrets.CONDA_UPLOAD_TOKEN_TAG }}

# ----------------------------------------------------------------------------
